spring:
  h2.console:
      enabled: true
      path: '/console'
  datasource:
    url: 'jdbc:h2:file:/home/daniel/ToDoList-SpringBoot/to-do-list/todo-db'
  jpa:
    hibernate.ddl-auto: create-drop
my.prop: 'test'

